settings:
  title: 'ecoeats Status'
  url: 'https://status.ecoeats.uk' # used for Slack messages
  logo: logo-192x192.png # image in ./public/ folder
  daysInHistogram: 90 # number of days you want to display in histogram
  collectResponseTimes: false # experimental feature, enable only for <5 monitors or on paid plans

  allmonitorsOperational: 'All Systems Operational'
  notAllmonitorsOperational: 'Issues Detected'
  monitorLabelOperational: 'Operational'
  monitorLabelNotOperational: 'Not Operational'
  monitorLabelNoData: 'No data'
  dayInHistogramNoData: 'No data'
  dayInHistogramOperational: 'All good'
  dayInHistogramNotOperational: ' incident(s)' # xx incident(s) recorded

monitors:
  - id: api # unique identifier
    name: api.ecoeats.uk
    description: 'Our main API' # default=empty
    url: 'https://api.ecoeats.uk/health' # URL to fetch
    method: GET # default=GET
    expectStatus: 200 # operational status, default=200
    followRedirect: false # should fetch follow redirects, default=false
    
  - id: blog # unique identifier
    name: blog.ecoeats.uk
    url: 'https://blog.ecoeats.uk' # URL to fetch
    method: GET # default=GET
    expectStatus: 200 # operational status, default=200
    followRedirect: false # should fetch follow redirects, default=false

  - id: postcodes # unique identifier
    name: postcodes.ecoeats.uk
    url: 'https://postcodes.ecoeats.uk' # URL to fetch
    method: GET # default=GET
    expectStatus: 200 # operational status, default=200
    followRedirect: false # should fetch follow redirects, default=false

  - id: tiles # unique identifier
    name: tiles.ecoeats.uk
    url: 'https://tiles.ecoeats.uk' # URL to fetch
    method: GET # default=GET
    expectStatus: 200 # operational status, default=200
    followRedirect: false # should fetch follow redirects, default=false
